import type { TenantRole } from "@prisma/client";

export const permissions = [
  "tenant.read",
  "tenant.manage",
  "branding.manage",
  "branch.read",
  "branch.manage",
  "member.read",
  "member.manage",
  "customer.read",
  "customer.manage",
  "supplier.read",
  "supplier.manage",
  "lab.read",
  "lab.manage",
  "lab.result",
  "lab.payment",
  "inventory.read",
  "inventory.manage",
  "sale.read",
  "sale.create",
  "sale.payment",
  "sale.return",
  "sale.void",
  "expense.read",
  "expense.manage",
  "expense.void",
  "report.read",
  "audit.read",
] as const;

export type Permission = (typeof permissions)[number];

const rolePermissions: Record<TenantRole, ReadonlySet<Permission>> = {
  OWNER: new Set(permissions),
  ADMIN: new Set(permissions.filter((permission) => permission !== "tenant.manage")),
  MANAGER: new Set([
    "tenant.read",
    "branch.read",
    "member.read",
    "customer.read",
    "customer.manage",
    "supplier.read",
    "supplier.manage",
    "lab.read",
    "lab.manage",
    "lab.result",
    "lab.payment",
    "inventory.read",
    "inventory.manage",
    "sale.read",
    "sale.create",
    "sale.payment",
    "sale.return",
    "sale.void",
    "expense.read",
    "expense.manage",
    "report.read",
    "audit.read",
  ]),
  PHARMACIST: new Set([
    "tenant.read",
    "branch.read",
    "customer.read",
    "customer.manage",
    "supplier.read",
    "lab.read",
    "lab.result",
    "inventory.read",
    "inventory.manage",
    "sale.read",
    "sale.create",
    "report.read",
  ]),
  CASHIER: new Set([
    "tenant.read",
    "branch.read",
    "customer.read",
    "customer.manage",
    "inventory.read",
    "sale.read",
    "sale.create",
  ]),
  AUDITOR: new Set([
    "tenant.read",
    "branch.read",
    "member.read",
    "customer.read",
    "supplier.read",
    "lab.read",
    "inventory.read",
    "expense.read",
    "report.read",
    "audit.read",
  ]),
};

export function roleHasPermission(role: TenantRole, permission: Permission) {
  return rolePermissions[role].has(permission);
}
