import type { TenantRole } from "@prisma/client";

export const permissions = [
  "tenant.read",
  "tenant.manage",
  "branding.manage",
  "branch.read",
  "branch.manage",
  "member.read",
  "member.manage",
  "customer.read",
  "customer.manage",
  "supplier.read",
  "supplier.manage",
  "clinic.read",
  "clinic.register",
  "clinic.payment",
  "clinic.consult",
  "clinic.complete",
  "clinic.sample",
  "patient.read",
  "patient.create",
  "clinic.assign",
  "clinic.history",
  "clinic.examine",
  "clinic.visit.lookup",
  "lab.order",
  "lab.order.read",
  "lab.catalog.read",
  "lab.sample.collect",
  "diagnosis.create",
  "lab.result.read",
  "lab.result.print",
  "payment.receipt.print",
  "sale.receipt.print",
  "patient.lookup",
  "patient.lab_identity.read",
  "lab.manage",
  "lab.result.create",
  "lab.result.complete",
  "lab.payment",
  "inventory.read",
  "inventory.manage",
  "sale.read",
  "sale.create",
  "sale.payment",
  "sale.return",
  "sale.void",
  "expense.read",
  "expense.manage",
  "expense.void",
  "report.read",
  "audit.read",
] as const;

export type Permission = (typeof permissions)[number];

const rolePermissions: Record<TenantRole, ReadonlySet<Permission>> = {
  OWNER: new Set(permissions),
  ADMIN: new Set(permissions.filter((permission) => permission !== "tenant.manage")),
  DOCTOR: new Set([
    "tenant.read",
    "branch.read",
    "clinic.read",
    "patient.read",
    "clinic.history",
    "clinic.consult",
    "clinic.complete",
    "clinic.examine",
    "lab.order.read",
    "lab.catalog.read",
    "lab.result.read",
    "lab.order",
    "diagnosis.create",
    "lab.result.print",
  ]),
  RECEPTIONIST: new Set([
    "tenant.read",
    "branch.read",
    "customer.read",
    "customer.manage",
    "clinic.read",
    "clinic.register",
    "clinic.payment",
    "clinic.assign",
    "clinic.history",
    "patient.read",
    "patient.create",
    "patient.lab_identity.read",
    "lab.order.read",
    "lab.payment",
    "payment.receipt.print",
  ]),
  PHARMACIST: new Set([
    "tenant.read",
    "branch.read",
    "supplier.read",
    "customer.read",
    "customer.manage",
    "clinic.visit.lookup",
    "patient.lookup",
    "sale.receipt.print",
    "inventory.read",
    "inventory.manage",
    "sale.read",
    "sale.create",
    "sale.payment",
  ]),
  LAB_TECHNICIAN: new Set([
    "tenant.read",
    "branch.read",
    "lab.order.read",
    "lab.catalog.read",
    "patient.lab_identity.read",
    "lab.sample.collect",
    "lab.result.read",
    "lab.result.create",
    "lab.result.complete",
    "lab.result.print",
  ]),
};

export function roleHasPermission(role: TenantRole, permission: Permission) {
  return rolePermissions[role].has(permission);
}
